"""Crear tabla horarios

Revision ID: ef440ac620d8
Revises: 
Create Date: 2025-04-10 15:26:13.220226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef440ac620d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('salon', sa.String(length=50), nullable=True),
    sa.Column('lunes', sa.Boolean(), nullable=True),
    sa.Column('martes', sa.Boolean(), nullable=True),
    sa.Column('miercoles', sa.Boolean(), nullable=True),
    sa.Column('jueves', sa.Boolean(), nullable=True),
    sa.Column('viernes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['Alumnos.id'], ),
    sa.ForeignKeyConstraint(['crn'], ['Materias.crn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.alter_column('certificado_preparatoria',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('comprobante_pago',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'Carreras', ['carrera_id'], ['id'])
        batch_op.create_foreign_key(None, 'EstadosAlumnos', ['estado_id'], ['id'])

    with op.batch_alter_table('Calificaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Cuatrimestres', ['cuatrimestre'], ['id'])
        batch_op.create_foreign_key(None, 'Materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])

    with op.batch_alter_table('Carga_Academica', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'Tipos_Carga_Academica', ['tipo_carga_id'], ['id'])
        batch_op.create_foreign_key(None, 'Materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'Cuatrimestres', ['cuatrimestre'], ['id'])

    with op.batch_alter_table('Docentes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['correo_electronico'])

    with op.batch_alter_table('EvaluacionesDocentes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Usuarios', ['id_docente'], ['id'])
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'Materias', ['materia_id'], ['id'])

    with op.batch_alter_table('Grupo_Alumno', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Grupos', ['grupo_id'], ['id'])
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])

    with op.batch_alter_table('Grupos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Carreras', ['carrera_id'], ['id'])

    with op.batch_alter_table('Materias', schema=None) as batch_op:
        batch_op.drop_index('idx_crn')
        batch_op.create_index(batch_op.f('ix_Materias_crn'), ['crn'], unique=True)
        batch_op.create_foreign_key(None, 'Materias', ['correlativa_id'], ['id'])

    with op.batch_alter_table('Notificaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])

    with op.batch_alter_table('Plan_Estudios', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Cuatrimestres', ['cuatrimestre'], ['id'])
        batch_op.create_foreign_key(None, 'Materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'Carreras', ['carrera_id'], ['id'])

    with op.batch_alter_table('Reportes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'Alumnos', ['alumno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Plan_Estudios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Materias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Materias_crn'))
        batch_op.create_index('idx_crn', ['crn'], unique=True)

    with op.batch_alter_table('Grupos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Grupo_Alumno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('EvaluacionesDocentes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Docentes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Carga_Academica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Calificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('comprobante_pago',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('certificado_preparatoria',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    op.drop_table('Horarios')
    # ### end Alembic commands ###
